/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "lsscsi"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "dgilbert@interlog.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "lsscsi"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "lsscsi 0.20"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lsscsi"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.20"

/* Version number of package */
#define VERSION "0.20"
